// Generated by CoffeeScript 1.7.1
var app, bodyParser, compress, config, cookieParser, express, logger, morgan, multer, path, render, routeRules, timerStr;

timerStr = 'blog程序启动用时';

console.time(timerStr);

path = require("path");

express = require("express");

morgan = require("morgan");

bodyParser = require("body-parser");

cookieParser = require("cookie-parser");

compress = require("compression");

multer = require("multer");

require('coffee-cache');

config = require("./config");

routeRules = require("./backend/route");

logger = require("./backend/base/log");

render = require("./backend/pageController/render");

app = express();

logger.info(config.photoLib);

logger.info(config.uploadTmp);

app.set("view engine", "jade");

app.set("views", path.join(__dirname, "views"));

if (config.env === "dev") {
  app.use(morgan("dev"));
}

app.use(bodyParser());

app.use(multer({
  dest: config.uploadTmp
}));

app.use(cookieParser());

app.use(express["static"](__dirname + "/public"));

routeRules.bind(app);

app.use(function(err, req, res, next) {
  if (err) {
    logger.error(err);
    if (req.path.indexOf("/app") === 0) {
      res.json({
        code: err.code || "500",
        msg: err
      });
    } else {
      res.redirect("/" + (err.code || '500'));
    }
  } else {
    next();
  }
});

app.listen(config.port, function() {
  logger.info("app is listeing @ : " + config.port);
  return console.timeEnd(timerStr);
});
